"""structural phylogeny: explicit implementation ownership."""
from __future__ import annotations

from collections import defaultdict
from intraphy.inference.ctmc import _ascertainment_log_probability
from intraphy.inference.ctmc import _compress_patterns
from intraphy.inference.ctmc import _dataset_log_likelihood
from intraphy.inference.ctmc import _inside_log_messages
from intraphy.inference.ctmc import _inside_messages
from intraphy.inference.ctmc import _iter_weighted_patterns
from intraphy.inference.ctmc import _log_array
from intraphy.inference.ctmc import _pattern_has_state_one
from intraphy.inference.ctmc import _pattern_log_likelihood
from intraphy.inference.ctmc import _pattern_observed_values
from intraphy.inference.ctmc import _root_prior
from intraphy.inference.ctmc import _selected_for_ascertainment
from intraphy.inference.ctmc import _transition_matrix
from intraphy.inference.diagnostics import _fit_output_row
from intraphy.inference.diagnostics import _fit_valid_for_posterior
from intraphy.inference.diagnostics import _lrt_unavailable_reason
from intraphy.inference.diagnostics import _posterior_sensitivity_status
from intraphy.inference.diagnostics import _posterior_unavailable_reason
from intraphy.inference.diagnostics import _unavailable_fit
from intraphy.inference.events import _transition_event_type
from intraphy.inference.events import _transition_structural_relation
from intraphy.inference.fitting import _no_patterns_reason
from intraphy.inference.fitting import _observed_information
from intraphy.inference.fitting import _profile_contrast_interval
from intraphy.inference.fitting import _profile_interval
from intraphy.inference.fitting import fit_model
from intraphy.inference.formatting import _bh_adjust
from intraphy.inference.formatting import _fmt
from intraphy.inference.inputs import _analysis_summary
from intraphy.inference.inputs import _load_site_matrix
from intraphy.inference.inputs import _masked_state
from intraphy.inference.inputs import _read_foreground_children
from intraphy.inference.inputs import _site_key
from intraphy.inference.inputs import _validate_complete_universe
from intraphy.inference.inputs import _validated_tree_rows
from intraphy.inference.layer_fitting import _fit_structural_layer
from intraphy.inference.likelihood_run import infer_single_copy_phylogeny
from intraphy.inference.model_comparison import _compare_structural_models
from intraphy.inference.parameters import COMPLETE_UNIVERSE_RULES
from intraphy.inference.parameters import GENERATED_ALL_ZERO_MASKS
from intraphy.inference.parameters import MULTIPLIER_MAX
from intraphy.inference.parameters import MULTIPLIER_MIN
from intraphy.inference.parameters import PROFILE_DROP_95
from intraphy.inference.parameters import RATE_MAX
from intraphy.inference.parameters import RATE_MIN
from intraphy.inference.parameters import _comparison_models
from intraphy.inference.parameters import _decode_parameters
from intraphy.inference.parameters import _model_bounds
from intraphy.inference.parameters import _model_starts
from intraphy.inference.posterior import _conditional_transition_count
from intraphy.inference.posterior import _expected_transition_count
from intraphy.inference.posterior import _posterior_messages
from intraphy.inference.posterior import _profile_posterior_envelope
from intraphy.inference.posterior_export import _append_structural_posteriors
from intraphy.observations.schema import STRUCTURAL_SITE_SCHEMA_VERSION
from intraphy.observations.schema import validate_structural_site_tip_rows
from intraphy.run_result import record_run_result
from intraphy.storage.tabular import write_tsv
from intraphy.structural_sites import build_structural_site_matrix
from intraphy.structural_sites import structural_matrix_annotation_view
from intraphy.topology import SpeciesTree
from pathlib import Path
from scipy.stats import chi2
import json
import math
import numpy as np


