"""mapping / fields: extracted responsibilities; see docs/architecture.md."""
from __future__ import annotations

from dataclasses import dataclass


SEGMENT_FIELDS = [
    "occurrence_id",
    "family_id",
    "species",
    "gene_copy_id",
    "transcript_id",
    "role",
    "role_set",
    "presence_status",
    "contig",
    "start",
    "end",
    "strand",
    "phase",
    "source_feature_id",
    "boundary_class",
    "splice_motif_score",
    "splice_donor",
    "splice_acceptor",
    "frame_status",
]


@dataclass(frozen=True)
class CorrespondenceCriteria:
    regular_min_coverage: float = 0.45
    high_identity_offset: float = 0.15
    high_identity_min_coverage: float = 0.30
    short_min_identity: float = 0.70
    short_min_query_coverage: float = 0.80
    short_min_aligned_pairs: int = 12


DEFAULT_CORRESPONDENCE_CRITERIA = CorrespondenceCriteria()


SEGMENT_OUTPUT_FIELDS = SEGMENT_FIELDS + ["source_label", "copy_role"]

SEGMENT_OUTPUT_FIELDS += [
    "transcript_order",
    "coding_status",
    "cds_start",
    "cds_end",
    "cds_length",
    "cds_phase",
    "cds_intervals",
    "utr_intervals",
    "utr_status",
    "source_feature_type",
    "source_parent",
    "source_parents",
    "feature_ownership",
    "path_roles",
    "coding_roles",
    "position_roles",
    "annotation_source",
    "original_attributes",
    "partial_start",
    "partial_end",
    "path_role_records",
]


TRANSCRIPT_PATH_FIELDS = [
    "path_id",
    "family_id",
    "species",
    "gene_copy_id",
    "transcript_id",
    "path_rank",
    "occurrence_id",
    "role",
    "contig",
    "start",
    "end",
    "strand",
    "phase",
    "transcript_order",
    "coding_status",
    "cds_length",
    "cds_phase",
    "cds_intervals",
    "utr_intervals",
    "path_status",
    "canonical_selection_rule",
    "source_feature_id",
    "source_feature_type",
    "path_role",
    "coding_role",
    "position_role",
    "annotation_source",
    "original_attributes",
    "partial_start",
    "partial_end",
]


RAW_FEATURE_FIELDS = [
    "family_id",
    "species",
    "gene_copy_id",
    "gene_id",
    "seqid",
    "source",
    "type",
    "start",
    "end",
    "strand",
    "phase",
    "id",
    "name",
    "parent",
    "parents",
    "ownership",
    "attrs",
]


INTRON_SITE_FIELDS = [
    "intron_id",
    "family_id",
    "species",
    "gene_copy_id",
    "transcript_id",
    "contig",
    "start",
    "end",
    "strand",
    "left_feature_id",
    "right_feature_id",
    "left_phase",
    "right_phase",
    "left_cds_length",
    "expected_right_phase",
    "phase_compatibility",
    "splice_donor",
    "splice_acceptor",
    "splice_motif_score",
]


GENE_LOCUS_FIELDS = [
    "species",
    "gene_copy_id",
    "contig",
    "strand",
    "annotation_start",
    "annotation_end",
    "linked_start",
    "linked_end",
    "search_start",
    "search_end",
    "contig_length",
    "genome_fasta",
    "max_extension",
    "range_status",
]


EXON_LIKE_ROLES = {"CDS", "exon", "UTR", "noncoding_exon"}


NONCODING_ROLES = {"intron", "intergenic"}


STRUCTURAL_ROLES = EXON_LIKE_ROLES | NONCODING_ROLES


UNKNOWN_SOURCE_LABELS = {"", "NA", "unknown", "unknown_source", "ambiguous", "unresolved"}


MATCH_FIELDS = [
    "match_id",
    "query_occurrence_id",
    "subject_occurrence_id",
    "alignment_score",
    "coverage_score",
    "sequence_score",
    "structural_context_score",
    "query_coverage",
    "target_coverage",
    "aligned_pairs",
    "query_alignment_start",
    "query_alignment_end",
    "target_alignment_start",
    "target_alignment_end",
    "query_mapped_contig",
    "query_mapped_start",
    "query_mapped_end",
    "query_mapped_strand",
    "query_mapped_length",
    "subject_mapped_contig",
    "subject_mapped_start",
    "subject_mapped_end",
    "subject_mapped_strand",
    "subject_mapped_length",
    "alignment_strand",
    "projected_reference_occurrence_id",
    "projected_reference_start",
    "projected_reference_end",
    "projected_reference_blocks",
    "matched_blocks",
    "query_genomic_matched_blocks",
    "subject_genomic_matched_blocks",
    "query_parent_feature_ids",
    "subject_parent_feature_ids",
    "query_transcript_ids",
    "subject_transcript_ids",
    "candidate_id",
    "alternative_candidate_ids",
    "aligned_blocks",
    "gap_blocks",
    "sequence_kind",
    "backend",
    "backend_version",
    "raw_score",
    "nt_identity",
    "aa_identity",
    "known_aligned_pairs",
    "unknown_aligned_pairs",
    "query_covered_bases",
    "target_covered_bases",
    "query_length",
    "target_length",
    "relative_strand",
    "is_secondary",
    "left_anchor_id",
    "right_anchor_id",
    "search_interval",
    "search_interval_side",
    "short_sequence_coverage",
    "alignment_input_transposed",
    "mapq",
    "mapping_quality",
    "hit_count",
    "ambiguous_hit_count",
    "alternative_hits",
    "candidate_assessments",
    "dna_candidate_assessments",
    "candidate_ids",
    "score_scheme",
    "raw_alignment_score",
    "enumeration_complete",
    "candidate_enumeration_status",
    "incomplete_reason",
    "short_context_route",
    "local_boundary_range",
    "candidate_resolution",
    "retained_candidate_ids",
    "best_path_candidate_ids",
    "chain_best_score",
    "chain_score_delta",
    "chain_configuration",
    "chain_delta_rule",
    "chain_local_mode",
    "chain_status",
    "chain_ambiguity",
    "chain_start_anchor_ids",
    "chain_end_anchor_ids",
    "chain_retained_edges",
    "chain_best_path_count_capped",
    "chain_near_optimal_path_count_capped",
    "flanking_anchor_status",
    "membership_edge_eligible",
    "membership_edge_reason",
    "position_edge_eligible",
    "position_edge_reason",
    "true_absence_eligible",
    "true_absence_evidence_status",
    "true_absence_reason",
    "left_context_score",
    "right_context_score",
    "boundary_score",
    "phase_score",
    "order_score",
    "strand_score",
    "splice_score",
    "size_ratio",
    "total_score",
    "distance_class",
    "threshold",
    "alignment_cigar",
    "alignment_backend",
    "match_status",
    "alignment_mode",
    "alignment_meaning",
    "alignment_requested_backend",
    "dna_match_status",
    "correspondence_basis",
    "correspondence_score",
    "protein_status",
    "protein_unavailable_reason",
    "protein_aa_identity",
    "protein_query_cds_coverage",
    "protein_target_cds_coverage",
    "protein_metrics_scope",
    "protein_best_query_transcript",
    "protein_best_target_transcript",
    "protein_supporting_transcripts",
    "protein_projected_blocks",
    "protein_mapping_status",
    "protein_candidate_evidence_available",
    "protein_membership_eligible",
    "protein_position_eligible",
    "protein_hard_observation_eligible",
    "protein_known_aa_pairs",
    "protein_blosum62_score",
    "protein_gap_fraction",
    "protein_left_anchor_pairs",
    "protein_right_anchor_pairs",
    "protein_left_anchor_score",
    "protein_right_anchor_score",
    "protein_left_anchor_supported",
    "protein_right_anchor_supported",
    "protein_terminal_side",
    "protein_msa_column_start0",
    "protein_msa_column_end0",
    "protein_msa_column_interval",
    "protein_msa_mode",
    "protein_candidate_mapping_count",
    "protein_candidate_coordinate_consensus",
    "protein_candidate_details",
    "protein_competing_occurrences",
    "protein_query_source_features",
    "protein_target_source_features",
]


def _transcript_id_set(row):
    return {token for token in str(row.get("transcript_id", "")).split(";") if token and token != "NA"}
